### PR TITLE
Why would you disable the issues?

### PR DESCRIPTION
**Pull request by damianstasik**
Nevermind, just use [Nunjucks](https://mozilla.github.io/nunjucks/), **swig is obsolete**.
Thanks @gemwuu!

### CODE REVIEW

**Comment by omguhh** [comment]
Does anyone have a copy of the documentation at least?

**Comment by 7oque** [comment]
https://github.com/node-swig/swig-templates

EDIT:
Sorry I didn't have enough time to comment before. First of all, I love this project and am very grateful for the input by all.
- It seems this fork has the most momentum: https://github.com/node-swig/swig-templates (I could be wrong plz correct me, it had a fix I needed 🍺 )
- The documentation is in the repo, but yes I also miss the website, especially for getting anyone new onboard with twig/django-esque templating using node... in the immediate short-term: http://web.archive.org/web/20160426004203/http://paularmstrong.github.io/swig/
- I agree with the opening post, and it looks like people would be willing to maintain this fantastic project.

Many thanks to all again. Love the project and contributions. Thanks so much!

<3

**Comment by nedkelly** [comment]
This is such a shame, I absolutely love this engine, and after spending half a day trying to swap it out for Twig (among others) I've found that it's not going to be that simple to replace.

I have to say thanks to Paul for creating this engine, I respect the decision to move on, but it would be extremely handy to have a lasting documentation page online even in a plain text format in the repo for projects that still rely on this engine.

**Comment by damtsnkff** [comment]
I started a repo in order to create a Github Page for the Documentation. [Starter - Swig Documentation Website](https://github.com/damtsnkff/swig-documentation.github.com)
This is incomplete yet, but the structure is set up. (It uses Jekyll and will be easy to maintain.)

This is will be a temporary fix for the website being offline, and if any of you want to contribute it would be awesome. 
Also, maybe we could merge it to this (or another) repo once it's done, in order to centralize the informations ?

**Comment by prakaashkpk** [comment]
I have just restored the original documentation here https://prakaashkpk.github.io/swig-docs/
Most of the links seems to be working. Also I am planning to contribute to this project in my spare time on the [forked version here](https://github.com/prakaashkpk/swig)

Please feel free to make any changes to the documentation if it is incorrect.

**Comment by loganvolkers** [comment]
@prakaashkpk Maybe you could consider joining forces with  https://github.com/node-swig/swig-templates/ instead of a separate fork?

To start you could help them with this issue: https://github.com/node-swig/swig-templates/issues/8

**Comment by redskyburning** [comment]
A few months back I created a static content system using swig, and everybody has loved it so far. Today I went to train a new employee using the docs only to find they were gone! Much respect to Paul and the rest for creating this and to the community for carrying the torch forward. If swig-templates is the successor then they have what support I can give, hopefully I can convince a few teammates to pitch in as well.

It would be nice to have the issues back however, there were some useful discussions in there to refer to, and could really help the effort going forward. Perhaps if Paul and/or members of the original team could pass this project onto new maintainers or anoint an official successor from the forks, the community could focus it's efforts better and have a better shot at keeping swig going. It would truly be a shame to see this project gather dust, it really works quite well and I've yet to find another node solution for django/twig style templating. Viva Swig!

**Comment by wszgxa** [comment]
https://wszgxa.github.io/swig/ 
the old documention

**Comment by zhangwentao** [comment]
the document page can't be access, wish someone can fix it.

**Comment by prakaashkpk** [comment]
@zhangwentao You can access the documentation in 
https://prakaashkpk.github.io/swig-docs/ or https://web.archive.org/web/20151217051834/http://paularmstrong.github.io/swig/ or
https://wszgxa.github.io/swig/

**Comment by gemwuu** [comment]
Since it will not be maintained anymore, which is such a pity, and I really appreciate 
Paul's effort, I personally recommend you guys the similar engine written by Mozilla, [nunjucks](https://github.com/mozilla/nunjucks)

**Comment by nedkelly** [comment]
@visualfanatic swig-templates is looking like it will keep swig alive. While nunjucks is looking promising it's still missing some pretty important features that will most likely rule it out for some, such as the ability to pass parameters to includes, a deal breaker for my current project. I'm committed to swig for the foreseeable future because it's core to the work I've been doing for the past 4 month's, it too late to turn back, I'll be supporting the swig-templates project if needed as I'm sure will a few others.

**Comment by redskyburning** [comment]
@nedkelly is right, nunjucks is nice but no params on includes is a deal breaker. I evaluated it before opting for swig, and the little omissions like that were what sealed the deal. Maintained or not, swig is still the best Js templating solution available. I'm going to be switching over to swig-templates in the near future.

**Comment by damianstasik** [comment]
@nedkelly @redskyburning I see, but instead of using `include`, you could just use `macro`. Here is an example:

**Old way**
`sections/header.html`

``` HTML
<header>
   <h1>{{ title }]</h1>
   <p>{{ description }}</p>
</header>
```

`pages/contact.html`

``` HTML
{% include "../sections/header.html" with { title: "Contact", description: "Test" } %}
<form>
...
</form>
```

**New way**
`layout.html`

``` html
{% macro header(title, description='') %}
<header>
   <h1>{{ title }]</h1>
   {% if description %}<p>{{ description }}</p>{% endif %}
</header>
{% endmacro %}

{% macro menu(links) %}
<nav>
   {% for link in links %}
   <a href="{{ link.url }}">{{ link.title }}</a>
   {% endfor %}
</nav>
{% endmacro %}
```

`pages/contact.html`

``` html
{% import "../layout.html" as layout %}

{{ layout.header('Contact') }}
<form>
...
</form>
```

I know that above example is stupidly simple, but it works. As I dig into Nunjucks issues I see that some stuff is missing, but you can easily add missing features using their API.

**Comment by Lochlan** [comment]
Docs are back online here: http://node-swig.github.io/swig-templates/

All contributions to our fork are welcome.  We're trying to get the project back into a good state for future development so any contributions towards that end would be appreciated.  It is unfortunate that the issues are gone from this repo, as we now have no good way of knowing what bugs remain—but, if anybody finds any, please file them in [our github issues](https://github.com/node-swig/swig-templates/issues) and/or submit a PR.  Thanks all, hopefully we can keep this great project alive!

**Pull request closed without merging**
