### PR TITLE
Export getLocals method

### PR DESCRIPTION
**Pull request by Javey**
Description #485

### CODE REVIEW

**Comment by zmetcalf** [comment]
To get around the limitation in Express, I created a 'context processor' file that would change the getLocals once. (Although it looks like I removed the other context processors) 

https://github.com/zmetcalf/chesterfield_express/blob/master/lib/context_processors.js

I just include it in my app here:
https://github.com/zmetcalf/chesterfield_express/blob/master/index.js#L135

**Comment by Javey** [comment]
Hmm... I want to change locals twice like below:
```js
app.use(function(req, res, next) {
    swig.setDefaults({locals: {reqpath: req.path}});
    next();
});

app.use(function(req, res, next) {
    // It will replace locals totally. 
    swig.setDefaults({locals: {logged_in: !!req.session.user}});
    // I want to get the locals, then I can extend it.
    // _.extend(swig.getLocals(), {logged_in: !!req.session.user});
    next();
});
```

**Comment by zmetcalf** [comment]
Totally agreed since I recommended it, but Paul was not super inclined to do anything about it. Now the project isn't maintained...

What is to stop you from just making those items one line of code:

    app.use(function(req, res, next) {
        swig.setDefaults({locals: {reqpath: req.path, logged_in: !!req.session.user}});
        next();
    });

**Comment by Javey** [comment]
> What is to stop you from just making those items one line of code

Because I add some data globally, then I add some other data for a group route.
But I found there is a problem when I add data asynchronously, and I resolved it by assigning data to `res.locals`. You can also get `res.locals` in swig template. Maybe this is the correct way.
```js
app.use(function(req, res, next) {
    res.locals = {locals: {reqpath: req.path, logged_in: !!req.session.user}};
    next();
});
```

**Pull request closed without merging**
